// <auto-generated />
using System;
using Ecommerce.Repository.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421122451_OrderItemTable")]
    partial class OrderItemTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.OrderItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClientId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83c56dde-acc1-4e4a-930f-c152beb33316"),
                            Brand = "MSI",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 164, DateTimeKind.Local).AddTicks(8952),
                            Description = "MSI Pulse GL66 15.6\" FHD 144Hz Gaming Laptop: Intel Core i7-12700H RTX 3070 16GB 512GB NVMe SSD",
                            ImageFileName = "22866337.jpg",
                            Name = "MSI Pulse",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("38984865-44ab-4854-b8d1-6ce79dca7379"),
                            Brand = "Acer",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7746),
                            Description = "Acer Swift X SFX14-42G-R607 Creator Laptop | 14\" Full HD 100% sRGB | AMD Ryzen 7 5825U",
                            ImageFileName = "84600886.jpg",
                            Name = "Acer Swift",
                            Price = 929.00m
                        },
                        new
                        {
                            Id = new Guid("1ff3cf5d-ff10-4ef0-8ab5-8d5748b1e38a"),
                            Brand = "Lenovo",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7775),
                            Description = "Lenovo 2022 Newest Ideapad 3 Laptop, 15.6\" HD Touchscreen, 11th Gen Intel Core i3-1115G4 Processor, 8GB DDR4 RAM, 256GB PCIe NVMe SSD",
                            ImageFileName = "10744695.jpg",
                            Name = "Lenovo Ideapad",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = new Guid("8ff50ca0-ef5a-4520-8841-4810a2898e80"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7781),
                            Description = "Dell Latitude 7000 7430 14\" Notebook - Full HD - 1920 x 1080 - Intel Core i7 12th Gen i7-1265U Deca-core (10 Core) 1.80 GHz",
                            ImageFileName = "81882367.jpg",
                            Name = "Dell Latitude 7000",
                            Price = 1199.00m
                        },
                        new
                        {
                            Id = new Guid("7681d19b-18ce-4b49-adce-8124206cf99d"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7784),
                            Description = "Dell Inspiron 15 3000 Series 3511 Laptop, 15.6\" FHD Touchscreen, Intel Core i5-1035G1, 32GB",
                            ImageFileName = "41732775.jpg",
                            Name = "Dell Inspiron 15",
                            Price = 989.00m
                        },
                        new
                        {
                            Id = new Guid("141d6472-cca0-413f-8199-fc3d83ec86bb"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7849),
                            Description = "Dell 2022 Newest Inspiron 3000 Laptop, 15.6 HD Display, Intel Celeron N4020 Processor, 8GB DDR4 RAM",
                            ImageFileName = "63529756.jpg",
                            Name = "Dell Inspiron 3000",
                            Price = 849.00m
                        },
                        new
                        {
                            Id = new Guid("86076172-8080-4ab5-a0cc-811d891cd900"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7854),
                            Description = "HP 14\" FHD Laptop for Business and Student, AMD Ryzen3 3250U (Beat i5 7200U), 16GB RAM",
                            ImageFileName = "10590390.jpg",
                            Name = "HP ENVY 200",
                            Price = 869.00m
                        },
                        new
                        {
                            Id = new Guid("4b1618ed-3a68-45e2-b5f9-434409377dc6"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7874),
                            Description = "HP 2023 15\" HD IPS Laptop, Windows 11, Intel Pentium 4-Core Processor Up to 2.70GHz, 8GB RAM",
                            ImageFileName = "92970713.jpg",
                            Name = "HP Pavilion 15",
                            Price = 789.00m
                        },
                        new
                        {
                            Id = new Guid("fd8e0f09-87e8-45b5-b091-4e0e5a189c64"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7878),
                            Description = "HP Newest 14\" HD Laptop, Windows 11, Intel Celeron Dual-Core Processor Up to 2.60GHz, 4GB RAM",
                            ImageFileName = "16303427.jpg",
                            Name = "HP ENVY 14\"",
                            Price = 779.00m
                        },
                        new
                        {
                            Id = new Guid("7c09454e-3d93-4d45-a94c-5ce977c991de"),
                            Brand = "Logitech",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7886),
                            Description = "Logitech MK345 Wireless Combo Full-Sized Keyboard with Palm Rest and Mouse",
                            ImageFileName = "83655305.jpg",
                            Name = "Keyboard MK345",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = new Guid("2c5bea69-ad71-42b8-a13d-0bf55ededca2"),
                            Brand = "Amazon",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7889),
                            Description = "Amazon Basics Wireless Computer Mouse with USB Nano Receiver - Black",
                            ImageFileName = "11677601.jpg",
                            Name = "Wireless Mouse",
                            Price = 39.00m
                        },
                        new
                        {
                            Id = new Guid("4cac9188-c6cf-493f-afbd-6abe5ef96603"),
                            Brand = "Lenovo",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7892),
                            Description = "Lenovo Laptop Shoulder Bag T210, 15.6-Inch Laptop or Tablet",
                            ImageFileName = "15587367.jpg",
                            Name = "Laptop Bag T210",
                            Price = 69.00m
                        },
                        new
                        {
                            Id = new Guid("2d697120-d6fe-43ba-91d4-e28fcc8c4be9"),
                            Brand = "Canon",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7895),
                            Description = "Canon Pixma MG3620 Wireless All-in-One Color Inkjet Printer with Mobile and Tablet Printing, Black",
                            ImageFileName = "12643487.jpg",
                            Name = "Canon Pixma MG3620",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = new Guid("287e5722-13be-4f59-beb5-2bff0563a8cd"),
                            Brand = "Brother",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7898),
                            Description = "Brother Compact Monochrome Laser Printer, HL-L2350DW, Wireless Printing",
                            ImageFileName = "89890247.jpg",
                            Name = "Brother HL-L2350DW",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = new Guid("dbfb0140-5201-4cc1-8dae-0f7e4ce7fe31"),
                            Brand = "Lexmark",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7901),
                            Description = "Lexmark B3442dw Black and White Laser Printer, Wireless with Ethernet, Mobile-Friendly and Cloud Connection",
                            ImageFileName = "91537624.jpg",
                            Name = "Lexmark B3442dw",
                            Price = 319.00m
                        },
                        new
                        {
                            Id = new Guid("c11a5664-0c2e-48d5-a464-a1ac1986da68"),
                            Brand = "Panasonic",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7908),
                            Description = "Panasonic LUMIX FZ80 4K Digital Camera, 18.1 Megapixel Video Camera, 60X Zoom",
                            ImageFileName = "66899970.jpg",
                            Name = "Panasonic LUMIX",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = new Guid("a28ebb6d-15b2-4fa4-a9b8-05e9473c68f4"),
                            Brand = "Kodak",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7931),
                            Description = "KODAK PIXPRO Friendly Zoom FZ55-BL 16MP Digital Camera with 5X Optical Zoom",
                            ImageFileName = "65286227.jpg",
                            Name = "KODAK PIXPRO",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("08b6203f-3bb1-4110-8cd7-e882124c6821"),
                            Brand = "Sony",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7938),
                            Description = "Sony CyberShot RX10 IV with 0.03 Second Auto-Focus & 25x Optical Zoom",
                            ImageFileName = "57415624.jpg",
                            Name = "Sony CyberShot",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = new Guid("0eb42362-283b-47e4-8dfe-56b6843f5d48"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7941),
                            Description = "Garmin DriveSmart 65, Built-In Voice-Controlled GPS Navigator with 6.95\" High-Res Display , Black",
                            ImageFileName = "75241241.jpg",
                            Name = "Garmin DriveSmart",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = new Guid("9cea55f6-c992-4dbd-818b-d5439cc4c7de"),
                            Brand = "Samsung",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7944),
                            Description = "SAMSUNG Galaxy SmartTag Bluetooth Smart Home Accessory Tracker, Attachment Locator for Lost Keys",
                            ImageFileName = "72426380.jpg",
                            Name = "SAMSUNG SmartTag",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = new Guid("0ccfb9a2-b6dc-44b5-baf3-c1bd604dfde5"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7947),
                            Description = "Garmin Instinct, Rugged Outdoor Watch with GPS, Features Glonass and Galileo",
                            ImageFileName = "35640104.jpg",
                            Name = "Garmin Instinct",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = new Guid("bf96c2fc-c086-4651-9e0a-b582c7afc058"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7950),
                            Description = "Apple iPhone 12, 64GB, Black - Unlocked and compatible with any carrier of choice on GSM and CDMA networks. Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.",
                            ImageFileName = "11736965.jpg",
                            Name = "iPhone 12",
                            Price = 969.00m
                        },
                        new
                        {
                            Id = new Guid("2b2597de-c3fb-43a7-af59-4d4ed36447e0"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7953),
                            Description = "Apple iPhone 13 Pro 512Go Graphite - Unlocked and compatible with any carrier of choice on GSM and CDMA networks.",
                            ImageFileName = "97815739.jpg",
                            Name = "iPhone 13",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = new Guid("c4b5c401-7998-4dfa-9b4e-727feb42bc41"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7959),
                            Description = "Apple iPhone 14 Pro 128GB Purple",
                            ImageFileName = "57380538.jpg",
                            Name = "iPhone 14",
                            Price = 969.80m
                        },
                        new
                        {
                            Id = new Guid("234eeceb-fcea-4435-8426-53125fbb8a1d"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7962),
                            Description = "Samsung Galaxy S5 16GB Black Unlocked",
                            ImageFileName = "80522267.jpg",
                            Name = "Samsung Galaxy S5",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("3887e458-cc01-4332-8693-64ed022a0d46"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7965),
                            Description = "SAMSUNG Galaxy S23 Cell Phone, Factory Unlocked Android Smartphone, 256GB Storage, 50MP Camera, Night Mode, Long Battery Life, Adaptive Display, US Version, 2023, Lavender",
                            ImageFileName = "66017605.jpg",
                            Name = "SAMSUNG Galaxy S23",
                            Price = 749.00m
                        },
                        new
                        {
                            Id = new Guid("f22c9273-6ce1-4815-9c2e-7cc8a6603f29"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7968),
                            Description = "SAMSUNG Galaxy Z Flip 3 5G Cell Phone, Factory Unlocked Android Smartphone, 256GB, Flex Mode, Super Steady Camera, Ultra Compact, US Version, Phantom Black",
                            ImageFileName = "10967363.jpg",
                            Name = "SAMSUNG Galaxy Z",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("cc463fdb-53df-4f58-b6fe-005e10cd328a"),
                            Brand = "Motorola",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7971),
                            Description = "Moto G Power | 2022 | 3-Day Battery | Unlocked | Made for US by Motorola | 4/128GB | 50 MP Camera | Ice Blue",
                            ImageFileName = "69725864.jpg",
                            Name = "Moto G Power",
                            Price = 699.00m
                        },
                        new
                        {
                            Id = new Guid("6c8ed629-778e-4232-8ddb-5d112fc958e6"),
                            Brand = "Nokia",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7974),
                            Description = "Nokia G10 | Android 11 | Unlocked Smartphone | 3-Day Battery | Dual SIM | US Version | 3/32GB | 6.52-Inch Screen | 13MP Triple Camera | Dusk",
                            ImageFileName = "46411326.jpg",
                            Name = "Nokia G10",
                            Price = 689.00m
                        },
                        new
                        {
                            Id = new Guid("d401fe1a-cda1-4e29-948f-3e6a02fde903"),
                            Brand = "OnePlus",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 24, 50, 166, DateTimeKind.Local).AddTicks(7978),
                            Description = "OnePlus Nord N20 5G | Android Smart Phone | 6.43\" AMOLED Display| 6+128GB | Unlocked | 4500 mAh Battery | 33W Fast Charging | Blue Smoke",
                            ImageFileName = "17327675.jpg",
                            Name = "OnePlus Nord N20",
                            Price = 899.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.OrderItems", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.Orders", null)
                        .WithMany("Items")
                        .HasForeignKey("OrdersId");

                    b.HasOne("Ecommerce.Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
