// <auto-generated />
using System;
using Ecommerce.Repository.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421122048_OrderTable")]
    partial class OrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edd586f9-4f8d-414c-9609-ab3335e43be9"),
                            Brand = "MSI",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 887, DateTimeKind.Local).AddTicks(5654),
                            Description = "MSI Pulse GL66 15.6\" FHD 144Hz Gaming Laptop: Intel Core i7-12700H RTX 3070 16GB 512GB NVMe SSD",
                            ImageFileName = "22866337.jpg",
                            Name = "MSI Pulse",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("c0083cba-3d38-4765-90fc-845283aca257"),
                            Brand = "Acer",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3558),
                            Description = "Acer Swift X SFX14-42G-R607 Creator Laptop | 14\" Full HD 100% sRGB | AMD Ryzen 7 5825U",
                            ImageFileName = "84600886.jpg",
                            Name = "Acer Swift",
                            Price = 929.00m
                        },
                        new
                        {
                            Id = new Guid("7711858d-fa68-48bc-a05f-886ac88fa9d9"),
                            Brand = "Lenovo",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3583),
                            Description = "Lenovo 2022 Newest Ideapad 3 Laptop, 15.6\" HD Touchscreen, 11th Gen Intel Core i3-1115G4 Processor, 8GB DDR4 RAM, 256GB PCIe NVMe SSD",
                            ImageFileName = "10744695.jpg",
                            Name = "Lenovo Ideapad",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = new Guid("c8d1b3a3-407f-4f97-bbf1-c664511b4c6e"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3635),
                            Description = "Dell Latitude 7000 7430 14\" Notebook - Full HD - 1920 x 1080 - Intel Core i7 12th Gen i7-1265U Deca-core (10 Core) 1.80 GHz",
                            ImageFileName = "81882367.jpg",
                            Name = "Dell Latitude 7000",
                            Price = 1199.00m
                        },
                        new
                        {
                            Id = new Guid("4224959d-44cd-428e-b4b7-6ba1dea721c2"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3640),
                            Description = "Dell Inspiron 15 3000 Series 3511 Laptop, 15.6\" FHD Touchscreen, Intel Core i5-1035G1, 32GB",
                            ImageFileName = "41732775.jpg",
                            Name = "Dell Inspiron 15",
                            Price = 989.00m
                        },
                        new
                        {
                            Id = new Guid("d7f7e488-479d-4392-8a68-a90aaa4b75bd"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3678),
                            Description = "Dell 2022 Newest Inspiron 3000 Laptop, 15.6 HD Display, Intel Celeron N4020 Processor, 8GB DDR4 RAM",
                            ImageFileName = "63529756.jpg",
                            Name = "Dell Inspiron 3000",
                            Price = 849.00m
                        },
                        new
                        {
                            Id = new Guid("75b40625-d0e7-47cd-9d07-87f2fe677df8"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3681),
                            Description = "HP 14\" FHD Laptop for Business and Student, AMD Ryzen3 3250U (Beat i5 7200U), 16GB RAM",
                            ImageFileName = "10590390.jpg",
                            Name = "HP ENVY 200",
                            Price = 869.00m
                        },
                        new
                        {
                            Id = new Guid("c30b5388-25c9-4b49-959d-33f7d473ab52"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3685),
                            Description = "HP 2023 15\" HD IPS Laptop, Windows 11, Intel Pentium 4-Core Processor Up to 2.70GHz, 8GB RAM",
                            ImageFileName = "92970713.jpg",
                            Name = "HP Pavilion 15",
                            Price = 789.00m
                        },
                        new
                        {
                            Id = new Guid("b509bb64-6fda-454c-ad6a-08dfd4d607d1"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3688),
                            Description = "HP Newest 14\" HD Laptop, Windows 11, Intel Celeron Dual-Core Processor Up to 2.60GHz, 4GB RAM",
                            ImageFileName = "16303427.jpg",
                            Name = "HP ENVY 14\"",
                            Price = 779.00m
                        },
                        new
                        {
                            Id = new Guid("e5093fdb-9b09-4b32-b22d-93772c38dfb3"),
                            Brand = "Logitech",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3693),
                            Description = "Logitech MK345 Wireless Combo Full-Sized Keyboard with Palm Rest and Mouse",
                            ImageFileName = "83655305.jpg",
                            Name = "Keyboard MK345",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = new Guid("901f9926-c73d-413a-86b6-1ab8b9b2db54"),
                            Brand = "Amazon",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3696),
                            Description = "Amazon Basics Wireless Computer Mouse with USB Nano Receiver - Black",
                            ImageFileName = "11677601.jpg",
                            Name = "Wireless Mouse",
                            Price = 39.00m
                        },
                        new
                        {
                            Id = new Guid("b4fb652e-032e-4a1f-b49d-7edcc8efe9d6"),
                            Brand = "Lenovo",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3699),
                            Description = "Lenovo Laptop Shoulder Bag T210, 15.6-Inch Laptop or Tablet",
                            ImageFileName = "15587367.jpg",
                            Name = "Laptop Bag T210",
                            Price = 69.00m
                        },
                        new
                        {
                            Id = new Guid("27a93fea-9a5e-4281-88ca-a680ab38e8d1"),
                            Brand = "Canon",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3703),
                            Description = "Canon Pixma MG3620 Wireless All-in-One Color Inkjet Printer with Mobile and Tablet Printing, Black",
                            ImageFileName = "12643487.jpg",
                            Name = "Canon Pixma MG3620",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = new Guid("de091249-509c-42d6-89c4-6a9444b9095c"),
                            Brand = "Brother",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3709),
                            Description = "Brother Compact Monochrome Laser Printer, HL-L2350DW, Wireless Printing",
                            ImageFileName = "89890247.jpg",
                            Name = "Brother HL-L2350DW",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = new Guid("4acaef9c-69ef-4b58-8d75-f33f3fc9ec41"),
                            Brand = "Lexmark",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3713),
                            Description = "Lexmark B3442dw Black and White Laser Printer, Wireless with Ethernet, Mobile-Friendly and Cloud Connection",
                            ImageFileName = "91537624.jpg",
                            Name = "Lexmark B3442dw",
                            Price = 319.00m
                        },
                        new
                        {
                            Id = new Guid("f260f6bb-5e00-4ec0-9490-60a15e063092"),
                            Brand = "Panasonic",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3734),
                            Description = "Panasonic LUMIX FZ80 4K Digital Camera, 18.1 Megapixel Video Camera, 60X Zoom",
                            ImageFileName = "66899970.jpg",
                            Name = "Panasonic LUMIX",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = new Guid("78547d9e-bd28-4572-9dfb-8142eb41d9f0"),
                            Brand = "Kodak",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3738),
                            Description = "KODAK PIXPRO Friendly Zoom FZ55-BL 16MP Digital Camera with 5X Optical Zoom",
                            ImageFileName = "65286227.jpg",
                            Name = "KODAK PIXPRO",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("8cb19f49-12b6-44bf-9ff0-f3cb7e4953c6"),
                            Brand = "Sony",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3742),
                            Description = "Sony CyberShot RX10 IV with 0.03 Second Auto-Focus & 25x Optical Zoom",
                            ImageFileName = "57415624.jpg",
                            Name = "Sony CyberShot",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = new Guid("2b6dd73c-a19e-46e3-a773-f55bea902021"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3746),
                            Description = "Garmin DriveSmart 65, Built-In Voice-Controlled GPS Navigator with 6.95\" High-Res Display , Black",
                            ImageFileName = "75241241.jpg",
                            Name = "Garmin DriveSmart",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = new Guid("a12ef6a6-b62a-4584-abfe-dda8fce89e1d"),
                            Brand = "Samsung",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3749),
                            Description = "SAMSUNG Galaxy SmartTag Bluetooth Smart Home Accessory Tracker, Attachment Locator for Lost Keys",
                            ImageFileName = "72426380.jpg",
                            Name = "SAMSUNG SmartTag",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = new Guid("2ebdd254-630c-43b1-b66d-746430420f87"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3752),
                            Description = "Garmin Instinct, Rugged Outdoor Watch with GPS, Features Glonass and Galileo",
                            ImageFileName = "35640104.jpg",
                            Name = "Garmin Instinct",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = new Guid("f9cad294-0a00-4f84-a813-b95c7140bbe9"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3759),
                            Description = "Apple iPhone 12, 64GB, Black - Unlocked and compatible with any carrier of choice on GSM and CDMA networks. Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.",
                            ImageFileName = "11736965.jpg",
                            Name = "iPhone 12",
                            Price = 969.00m
                        },
                        new
                        {
                            Id = new Guid("40c02982-56a5-4551-9e6d-6bf365f8bf1e"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3762),
                            Description = "Apple iPhone 13 Pro 512Go Graphite - Unlocked and compatible with any carrier of choice on GSM and CDMA networks.",
                            ImageFileName = "97815739.jpg",
                            Name = "iPhone 13",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = new Guid("5322e5d5-93e2-4d8e-9736-5cc87404c002"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3765),
                            Description = "Apple iPhone 14 Pro 128GB Purple",
                            ImageFileName = "57380538.jpg",
                            Name = "iPhone 14",
                            Price = 969.80m
                        },
                        new
                        {
                            Id = new Guid("7302cb27-9e9b-4676-9598-fa7f4c1b4215"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3768),
                            Description = "Samsung Galaxy S5 16GB Black Unlocked",
                            ImageFileName = "80522267.jpg",
                            Name = "Samsung Galaxy S5",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("e6931099-0f21-497b-8865-175ec4340520"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3771),
                            Description = "SAMSUNG Galaxy S23 Cell Phone, Factory Unlocked Android Smartphone, 256GB Storage, 50MP Camera, Night Mode, Long Battery Life, Adaptive Display, US Version, 2023, Lavender",
                            ImageFileName = "66017605.jpg",
                            Name = "SAMSUNG Galaxy S23",
                            Price = 749.00m
                        },
                        new
                        {
                            Id = new Guid("aefc7699-746c-4a59-8b18-e8252574dd2c"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3774),
                            Description = "SAMSUNG Galaxy Z Flip 3 5G Cell Phone, Factory Unlocked Android Smartphone, 256GB, Flex Mode, Super Steady Camera, Ultra Compact, US Version, Phantom Black",
                            ImageFileName = "10967363.jpg",
                            Name = "SAMSUNG Galaxy Z",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("4ad0d1f5-8451-4f29-815a-2240485c48e7"),
                            Brand = "Motorola",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3778),
                            Description = "Moto G Power | 2022 | 3-Day Battery | Unlocked | Made for US by Motorola | 4/128GB | 50 MP Camera | Ice Blue",
                            ImageFileName = "69725864.jpg",
                            Name = "Moto G Power",
                            Price = 699.00m
                        },
                        new
                        {
                            Id = new Guid("75780ebb-6b80-414f-aee1-10fd4b342588"),
                            Brand = "Nokia",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3781),
                            Description = "Nokia G10 | Android 11 | Unlocked Smartphone | 3-Day Battery | Dual SIM | US Version | 3/32GB | 6.52-Inch Screen | 13MP Triple Camera | Dusk",
                            ImageFileName = "46411326.jpg",
                            Name = "Nokia G10",
                            Price = 689.00m
                        },
                        new
                        {
                            Id = new Guid("5f55820d-fbc7-452f-ad42-b9be5302cae3"),
                            Brand = "OnePlus",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 21, 18, 20, 43, 889, DateTimeKind.Local).AddTicks(3787),
                            Description = "OnePlus Nord N20 5G | Android Smart Phone | 6.43\" AMOLED Display| 6+128GB | Unlocked | 4500 mAh Battery | 33W Fast Charging | Blue Smoke",
                            ImageFileName = "17327675.jpg",
                            Name = "OnePlus Nord N20",
                            Price = 899.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
