// <auto-generated />
using System;
using Ecommerce.Repository.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.OrderItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrdersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingFee")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(16, 2)
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3035ec77-44dd-414b-9ecc-08a10d98bb51"),
                            Brand = "MSI",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 187, DateTimeKind.Local).AddTicks(6731),
                            Description = "MSI Pulse GL66 15.6\" FHD 144Hz Gaming Laptop: Intel Core i7-12700H RTX 3070 16GB 512GB NVMe SSD",
                            ImageFileName = "22866337.jpg",
                            Name = "MSI Pulse",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("b75b5318-33de-4d70-9098-cf792e7c39fe"),
                            Brand = "Acer",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5390),
                            Description = "Acer Swift X SFX14-42G-R607 Creator Laptop | 14\" Full HD 100% sRGB | AMD Ryzen 7 5825U",
                            ImageFileName = "84600886.jpg",
                            Name = "Acer Swift",
                            Price = 929.00m
                        },
                        new
                        {
                            Id = new Guid("bcfa15f3-2a86-4ce6-97df-2d804e0c6a32"),
                            Brand = "Lenovo",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5429),
                            Description = "Lenovo 2022 Newest Ideapad 3 Laptop, 15.6\" HD Touchscreen, 11th Gen Intel Core i3-1115G4 Processor, 8GB DDR4 RAM, 256GB PCIe NVMe SSD",
                            ImageFileName = "10744695.jpg",
                            Name = "Lenovo Ideapad",
                            Price = 799.00m
                        },
                        new
                        {
                            Id = new Guid("4bca63ad-a189-4141-8de0-d2230781f1d5"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5435),
                            Description = "Dell Latitude 7000 7430 14\" Notebook - Full HD - 1920 x 1080 - Intel Core i7 12th Gen i7-1265U Deca-core (10 Core) 1.80 GHz",
                            ImageFileName = "81882367.jpg",
                            Name = "Dell Latitude 7000",
                            Price = 1199.00m
                        },
                        new
                        {
                            Id = new Guid("2b8b21a1-3abc-48d6-ba5d-93d18a891110"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5465),
                            Description = "Dell Inspiron 15 3000 Series 3511 Laptop, 15.6\" FHD Touchscreen, Intel Core i5-1035G1, 32GB",
                            ImageFileName = "41732775.jpg",
                            Name = "Dell Inspiron 15",
                            Price = 989.00m
                        },
                        new
                        {
                            Id = new Guid("d62a6cb9-977b-48ca-86bd-347e0cd4d3eb"),
                            Brand = "Dell",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5487),
                            Description = "Dell 2022 Newest Inspiron 3000 Laptop, 15.6 HD Display, Intel Celeron N4020 Processor, 8GB DDR4 RAM",
                            ImageFileName = "63529756.jpg",
                            Name = "Dell Inspiron 3000",
                            Price = 849.00m
                        },
                        new
                        {
                            Id = new Guid("127fe090-b4fa-4ddc-87e1-1ac68ecac3b3"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5493),
                            Description = "HP 14\" FHD Laptop for Business and Student, AMD Ryzen3 3250U (Beat i5 7200U), 16GB RAM",
                            ImageFileName = "10590390.jpg",
                            Name = "HP ENVY 200",
                            Price = 869.00m
                        },
                        new
                        {
                            Id = new Guid("416eb64c-9ec5-486d-9c25-c47b0d4af2f5"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5499),
                            Description = "HP 2023 15\" HD IPS Laptop, Windows 11, Intel Pentium 4-Core Processor Up to 2.70GHz, 8GB RAM",
                            ImageFileName = "92970713.jpg",
                            Name = "HP Pavilion 15",
                            Price = 789.00m
                        },
                        new
                        {
                            Id = new Guid("69af4059-050f-454c-90e0-ed9608388ecb"),
                            Brand = "HP",
                            Category = "Computers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5505),
                            Description = "HP Newest 14\" HD Laptop, Windows 11, Intel Celeron Dual-Core Processor Up to 2.60GHz, 4GB RAM",
                            ImageFileName = "16303427.jpg",
                            Name = "HP ENVY 14\"",
                            Price = 779.00m
                        },
                        new
                        {
                            Id = new Guid("10a6495a-d798-4881-8a1c-c32b644d7a1d"),
                            Brand = "Logitech",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5515),
                            Description = "Logitech MK345 Wireless Combo Full-Sized Keyboard with Palm Rest and Mouse",
                            ImageFileName = "83655305.jpg",
                            Name = "Keyboard MK345",
                            Price = 59.00m
                        },
                        new
                        {
                            Id = new Guid("5145675b-baaf-4074-8599-a0f67feba7df"),
                            Brand = "Amazon",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5568),
                            Description = "Amazon Basics Wireless Computer Mouse with USB Nano Receiver - Black",
                            ImageFileName = "11677601.jpg",
                            Name = "Wireless Mouse",
                            Price = 39.00m
                        },
                        new
                        {
                            Id = new Guid("455e1a8f-3898-4b9e-b2da-58260eb0b67b"),
                            Brand = "Lenovo",
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5576),
                            Description = "Lenovo Laptop Shoulder Bag T210, 15.6-Inch Laptop or Tablet",
                            ImageFileName = "15587367.jpg",
                            Name = "Laptop Bag T210",
                            Price = 69.00m
                        },
                        new
                        {
                            Id = new Guid("1bade792-9c50-4164-a2e5-b851f3d2336e"),
                            Brand = "Canon",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5589),
                            Description = "Canon Pixma MG3620 Wireless All-in-One Color Inkjet Printer with Mobile and Tablet Printing, Black",
                            ImageFileName = "12643487.jpg",
                            Name = "Canon Pixma MG3620",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = new Guid("cf5226c9-6bb1-4043-93f9-3f9170bbe112"),
                            Brand = "Brother",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5595),
                            Description = "Brother Compact Monochrome Laser Printer, HL-L2350DW, Wireless Printing",
                            ImageFileName = "89890247.jpg",
                            Name = "Brother HL-L2350DW",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = new Guid("c7221f74-b6b9-4082-8bce-f58f4853087e"),
                            Brand = "Lexmark",
                            Category = "Printers",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5601),
                            Description = "Lexmark B3442dw Black and White Laser Printer, Wireless with Ethernet, Mobile-Friendly and Cloud Connection",
                            ImageFileName = "91537624.jpg",
                            Name = "Lexmark B3442dw",
                            Price = 319.00m
                        },
                        new
                        {
                            Id = new Guid("467c4180-94c4-44e5-a9ba-03d514fd6c6c"),
                            Brand = "Panasonic",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5606),
                            Description = "Panasonic LUMIX FZ80 4K Digital Camera, 18.1 Megapixel Video Camera, 60X Zoom",
                            ImageFileName = "66899970.jpg",
                            Name = "Panasonic LUMIX",
                            Price = 499.00m
                        },
                        new
                        {
                            Id = new Guid("659a31ce-60f7-444c-99aa-de29297ca7d1"),
                            Brand = "Kodak",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5612),
                            Description = "KODAK PIXPRO Friendly Zoom FZ55-BL 16MP Digital Camera with 5X Optical Zoom",
                            ImageFileName = "65286227.jpg",
                            Name = "KODAK PIXPRO",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("32485c24-bfb1-4935-880d-2b656fc1f051"),
                            Brand = "Sony",
                            Category = "Cameras",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5622),
                            Description = "Sony CyberShot RX10 IV with 0.03 Second Auto-Focus & 25x Optical Zoom",
                            ImageFileName = "57415624.jpg",
                            Name = "Sony CyberShot",
                            Price = 999.00m
                        },
                        new
                        {
                            Id = new Guid("24a68e06-efef-4d93-a0f6-a2f8902af059"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5627),
                            Description = "Garmin DriveSmart 65, Built-In Voice-Controlled GPS Navigator with 6.95\" High-Res Display , Black",
                            ImageFileName = "75241241.jpg",
                            Name = "Garmin DriveSmart",
                            Price = 199.00m
                        },
                        new
                        {
                            Id = new Guid("2928e7d6-3fc6-47f5-9d38-d73f03cf22e0"),
                            Brand = "Samsung",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5632),
                            Description = "SAMSUNG Galaxy SmartTag Bluetooth Smart Home Accessory Tracker, Attachment Locator for Lost Keys",
                            ImageFileName = "72426380.jpg",
                            Name = "SAMSUNG SmartTag",
                            Price = 89.00m
                        },
                        new
                        {
                            Id = new Guid("4f08c492-1989-4c4e-a96f-59d901252624"),
                            Brand = "Garmin",
                            Category = "Other",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5643),
                            Description = "Garmin Instinct, Rugged Outdoor Watch with GPS, Features Glonass and Galileo",
                            ImageFileName = "35640104.jpg",
                            Name = "Garmin Instinct",
                            Price = 79.00m
                        },
                        new
                        {
                            Id = new Guid("969a2406-bf57-4a46-9820-f4d4dc892afe"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5649),
                            Description = "Apple iPhone 12, 64GB, Black - Unlocked and compatible with any carrier of choice on GSM and CDMA networks. Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.",
                            ImageFileName = "11736965.jpg",
                            Name = "iPhone 12",
                            Price = 969.00m
                        },
                        new
                        {
                            Id = new Guid("7881fdb9-f6da-4d06-b97c-96348f21d0bd"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5657),
                            Description = "Apple iPhone 13 Pro 512Go Graphite - Unlocked and compatible with any carrier of choice on GSM and CDMA networks.",
                            ImageFileName = "97815739.jpg",
                            Name = "iPhone 13",
                            Price = 1299.00m
                        },
                        new
                        {
                            Id = new Guid("8e158843-52be-4ca4-8081-35e612e20ace"),
                            Brand = "Apple",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5669),
                            Description = "Apple iPhone 14 Pro 128GB Purple",
                            ImageFileName = "57380538.jpg",
                            Name = "iPhone 14",
                            Price = 969.80m
                        },
                        new
                        {
                            Id = new Guid("1df60045-1746-4369-a504-8fe7050841c2"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5675),
                            Description = "Samsung Galaxy S5 16GB Black Unlocked",
                            ImageFileName = "80522267.jpg",
                            Name = "Samsung Galaxy S5",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("b8ad36f5-7d08-4b1a-8a54-95a359064acb"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5680),
                            Description = "SAMSUNG Galaxy S23 Cell Phone, Factory Unlocked Android Smartphone, 256GB Storage, 50MP Camera, Night Mode, Long Battery Life, Adaptive Display, US Version, 2023, Lavender",
                            ImageFileName = "66017605.jpg",
                            Name = "SAMSUNG Galaxy S23",
                            Price = 749.00m
                        },
                        new
                        {
                            Id = new Guid("a8329993-e6d8-4962-b348-643dba15d013"),
                            Brand = "Samsung",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5686),
                            Description = "SAMSUNG Galaxy Z Flip 3 5G Cell Phone, Factory Unlocked Android Smartphone, 256GB, Flex Mode, Super Steady Camera, Ultra Compact, US Version, Phantom Black",
                            ImageFileName = "10967363.jpg",
                            Name = "SAMSUNG Galaxy Z",
                            Price = 899.00m
                        },
                        new
                        {
                            Id = new Guid("73c66dc3-86fe-4988-b4b4-8dd9651f5e3f"),
                            Brand = "Motorola",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5692),
                            Description = "Moto G Power | 2022 | 3-Day Battery | Unlocked | Made for US by Motorola | 4/128GB | 50 MP Camera | Ice Blue",
                            ImageFileName = "69725864.jpg",
                            Name = "Moto G Power",
                            Price = 699.00m
                        },
                        new
                        {
                            Id = new Guid("8a08c409-0348-4f78-b6c4-75724452623f"),
                            Brand = "Nokia",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5702),
                            Description = "Nokia G10 | Android 11 | Unlocked Smartphone | 3-Day Battery | Dual SIM | US Version | 3/32GB | 6.52-Inch Screen | 13MP Triple Camera | Dusk",
                            ImageFileName = "46411326.jpg",
                            Name = "Nokia G10",
                            Price = 689.00m
                        },
                        new
                        {
                            Id = new Guid("177b2438-178e-40a5-92c5-12e680ed1e88"),
                            Brand = "OnePlus",
                            Category = "Phones",
                            CreatedAt = new DateTime(2025, 4, 22, 16, 38, 6, 190, DateTimeKind.Local).AddTicks(5708),
                            Description = "OnePlus Nord N20 5G | Android Smart Phone | 6.43\" AMOLED Display| 6+128GB | Unlocked | 4500 mAh Battery | 33W Fast Charging | Blue Smoke",
                            ImageFileName = "17327675.jpg",
                            Name = "OnePlus Nord N20",
                            Price = 899.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Web.Models.OrderItems", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.Orders", null)
                        .WithMany("Items")
                        .HasForeignKey("OrdersId");

                    b.HasOne("Ecommerce.Web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Web.Models.Orders", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
